strani = ['Brazil','China','GB','Sirya','Island']
print(strani)
print(sorted(strani))
print(strani)
print(sorted(strani,reverse=True))
print(strani)
strani.reverse()
print(strani)
strani.reverse()
print(strani)
strani.sort()
print(strani)
strani.sort(reverse=True)
print(strani)

